baseURL = 'https://cantinho.neocities.org/'
defaultContentLanguage  = 'pt'
defaultContentLanguageInSubdir = false
theme = 'cantinho'


[languages]
  [languages.pt]
    contentDir = 'content/pt'
    disabled = false
    languageCode = 'pt-BR'
    languageDirection = 'ltr'
    languageName = '🇧🇷'
    title = 'Cantinho'
    weight = 1

  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = '🇺🇸'
    title = 'Little Corner'
    weight = 2

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
